
export const JOIN_FORM_UPDATE = 'JOIN_FORM_UPDATE';

export const REQUEST_CREATE_MEMBER = 'REQUEST_CREATE_MEMBER';
export const CREATE_MEMBER = 'CREATE_MEMBER';

export const REQUEST_READALL_MEMBER = 'REQUEST_READALL_MEMBER';
export const READALL_MEMBER = 'READALL_MEMBER';

export const IN_PROGRESSING = 'IN_PROGRESSING';
export const END_PROGRESSING = 'END_PROGRESSING';

export const FAIL_RECIEVED = 'FAIL_RECIEVED';